"""widen weight columns to numeric(8,4) for kg-precision round-tripping

Revision ID: 1a01854fdc3a
Revises: 55f39fee44ca
Create Date: 2026-09-27 14:46:36.215736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a01854fdc3a'
down_revision = '55f39fee44ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bodyweight_entries', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('template_exercises', schema=None) as batch_op:
        batch_op.alter_column('target_weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('body_weight',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('body_weight',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('template_exercises', schema=None) as batch_op:
        batch_op.alter_column('target_weight',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('bodyweight_entries', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
