"""initial schema

Revision ID: 55f39fee44ca
Revises: 
Create Date: 2026-09-27 11:00:21.625322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f39fee44ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodyweight_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('lbs', 'kg', name='bodyweight_unit', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recorded_at')
    )
    op.create_table('muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_unit', sa.Enum('lbs', 'kg', name='settings_weight_unit', native_enum=False), nullable=False),
    sa.Column('distance_unit', sa.Enum('mi', 'km', name='settings_distance_unit', native_enum=False), nullable=False),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Enum('system', 'light', 'dark', name='settings_theme', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.Enum('barbell', 'dumbbell', 'machine', 'cable', 'bodyweight', 'kettlebell', 'other', name='equipment_type', native_enum=False), nullable=False),
    sa.Column('tracking_type', sa.Enum('weight_reps', 'bodyweight_reps', 'time', 'cardio', name='tracking_type', native_enum=False), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('default_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'muscle_group_id', name='uq_exercise_name_group')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('body_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.String(length=32), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weight_unit', sa.Enum('lbs', 'kg', name='set_weight_unit', native_enum=False), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_dropset', sa.Boolean(), nullable=False),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_sets')
    op.drop_table('workout_exercises')
    op.drop_table('template_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    op.drop_table('workout_templates')
    op.drop_table('user_settings')
    op.drop_table('muscle_groups')
    op.drop_table('bodyweight_entries')
    # ### end Alembic commands ###
